<?php

/**
 * BaseVideo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $link
 * @property string $title
 * @property string $description
 * 
 * @method string getLink()        Returns the current record's "link" value
 * @method string getTitle()       Returns the current record's "title" value
 * @method string getDescription() Returns the current record's "description" value
 * @method Video  setLink()        Sets the current record's "link" value
 * @method Video  setTitle()       Sets the current record's "title" value
 * @method Video  setDescription() Sets the current record's "description" value
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVideo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('videos');
        $this->hasColumn('link', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('title', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('description', 'string', 400, array(
             'type' => 'string',
             'length' => 400,
             'notnull' => true,
             'unique' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}