<?php

/**
 * BaseFoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $filename
 * @property integer $car_id
 * @property boolean $is_primary
 * @property Car $Car
 * 
 * @method text    getFilename()   Returns the current record's "filename" value
 * @method integer getCarId()      Returns the current record's "car_id" value
 * @method boolean getIsPrimary()  Returns the current record's "is_primary" value
 * @method Car     getCar()        Returns the current record's "Car" value
 * @method Foto    setFilename()   Sets the current record's "filename" value
 * @method Foto    setCarId()      Sets the current record's "car_id" value
 * @method Foto    setIsPrimary()  Sets the current record's "is_primary" value
 * @method Foto    setCar()        Sets the current record's "Car" value
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fotos');
        $this->hasColumn('filename', 'text', 1024, array(
             'type' => 'text',
             'length' => 1024,
             ));
        $this->hasColumn('car_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_primary', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Car', array(
             'local' => 'car_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}