<?php

/**
 * BaseEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $date_start
 * @property timestamp $date_end
 * @property string $country
 * @property string $place
 * @property string $location
 * @property string $event
 * 
 * @method timestamp getDateStart()  Returns the current record's "date_start" value
 * @method timestamp getDateEnd()    Returns the current record's "date_end" value
 * @method string    getCountry()    Returns the current record's "country" value
 * @method string    getPlace()      Returns the current record's "place" value
 * @method string    getLocation()   Returns the current record's "location" value
 * @method string    getEvent()      Returns the current record's "event" value
 * @method Event     setDateStart()  Sets the current record's "date_start" value
 * @method Event     setDateEnd()    Sets the current record's "date_end" value
 * @method Event     setCountry()    Sets the current record's "country" value
 * @method Event     setPlace()      Sets the current record's "place" value
 * @method Event     setLocation()   Sets the current record's "location" value
 * @method Event     setEvent()      Sets the current record's "event" value
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('events');
        $this->hasColumn('date_start', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('date_end', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('country', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('place', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('location', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('event', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             'notnull' => true,
             'unique' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}