<?php

/**
 * BaseNews
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $msgtitle
 * @property text $msgbody
 * 
 * @method string getMsgtitle() Returns the current record's "msgtitle" value
 * @method text   getMsgbody()  Returns the current record's "msgbody" value
 * @method News   setMsgtitle() Sets the current record's "msgtitle" value
 * @method News   setMsgbody()  Sets the current record's "msgbody" value
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNews extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news');
        $this->hasColumn('msgtitle', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             'notnull' => true,
             'unique' => false,
             ));
        $this->hasColumn('msgbody', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'msgtitle',
              1 => 'msgbody',
             ),
             ));
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'name' => 'title_slug',
             'alias' => 'slug',
             'unique' => true,
             'fields' => 
             array(
              0 => 'msgtitle',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($i18n0);
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}