<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/22 22:56:44
sfConfig::add(array(
  'app_enabled_modules' => array (
  0 => 'default',
  1 => 'sfGuardAuth',
),
  'app_fb_fanpage' => 'http://www.facebook.com/thomascloudofficial',
  'app_fb_profile_owner' => 326936624056135,
  'app_fb_custom_css' => '/css/custom-fb.css',
  'app_yt_channel' => 'http://www.youtube.com/thomascloudofficial',
  'app_cloud_page' => 'http://soundcloud.com/thomascloudofficial',
  'app_twitter' => 'https://twitter.com/realthomascloud',
));
