<?php

/**
 * car
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Car extends BaseCar
{
    public function getPrimaryFoto()
    {
        $dir = "/uploads/";
        $fotos = $this->getFotos();
        
        foreach($fotos as $foto){
            if($foto->getIsPrimary())
            {
                return $dir.$foto->getFilename();
            }
        }
        
        return $dir.$fotos[0]->getFilename();
        
    }
}
