<?php

/**
 * carTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CarTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object carTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Car');
    }

    public static function getCarsQuery() {
        $query = self::getInstance()->createQuery("c");

        return $query;
    }

    public static function addSortOrder(Doctrine_Query $query, $column) {
        $query->orderBy($column);
        return $query;
    }

    public static function addModel(Doctrine_Query $query, $modelId) {
        $query->addWhere("c.model_id = ?",$modelId);
        return $query;
    }
    public static function addVariant(Doctrine_Query $query, $variantId) {
        $query->addWhere("c.variant_id = ?",$variantId);
        return $query;
    }
    public static function addSlider(Doctrine_Query $query) {
        $query->addWhere("c.slider = true");
        return $query;
    }
    public static function addPromoted(Doctrine_Query $query) {
        $query->addWhere("c.promoted = true");
        return $query;
    }
    public static function addBrand(Doctrine_Query $query, $brand) {
        $query->leftJoin("c.Model m");
        $query->addWhere("m.brand = ?",$brand);
        return $query;
    }
    
    public function getSliderCars()
    {
        $query = $this->getCarsQuery();
        self::addSortOrder($query, "created_at DESC");
        self::addSlider($query);
        return $query->execute();
    }
    
    public function getPromotedCars()
    {
        $query = $this->getCarsQuery();
        self::addSortOrder($query, "created_at DESC");
        self::addPromoted($query);
        return $query->execute();
    }
    
    public function getPromotedCarsQuery()
    {
        $query = $this->getCarsQuery();
        self::addSortOrder($query, "created_at DESC");
        self::addPromoted($query);
        return $query;
    }

}