<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Event extends BaseEvent {

    public static $countries = array(
        null => "wybierz kraj",
        1 => "argentyna",
        2 => "armenia",
        3 => "australia",
        4 => "austria",
        5 => "belgia",
        6 => "bialorus",
        7 => "brazylia",
        8 => "bulgaria",
        9 => "chorwacja",
        10 => "czechy",
        11 => "dania",
        12 => "egipt",
        13 => "estonia",
        14 => "finlandia",
        15 => "francja",
        16 => "grecja",
        17 => "hiszpania",
        18 => "holandia",
        19 => "iralndia",
        20 => "japonia",
        21 => "kanada",
        22 => "litwa",
        23 => "luksemburg",
        24 => "malta",
        25 => "moldawia",
        26 => "monako",
        27 => "niemcy",
        28 => "norwegia",
        29 => "polska",
        30 => "portugalia",
        31 => "rosja",
        32 => "rumunia",
        33 => "slowacja",
        34 => "slowenia",
        35 => "szwajcaria",
        36 => "szwecja",
        37 => "turcja",
        38 => "ukraina",
        39 => "usa",
        40 => "wegry",
        41 => "wlk-bryt",
        42 => "wlochy",
    );

    public function getDateStart() {
        $date = $this->isNew() ? date('Y-M-d H:i:s') : $this->_data["date_start"];
        return date("d.m.Y H:i", strtotime($date));
    }
    public function getDateEnd() {
        $date = $this->isNew() ? date('Y-M-d H:i:s') : $this->_data["date_end"];
        return date("d.m.Y H:i", strtotime($date));
    }

//    public function setDate($date) {
//        $this->_data["date"] = date("Y-M-d 12:00:00", strtotime($date));
//        file_put_contents('/var/www/thomascloud.local/test_'.microtime().'.txt',$date);
//    }
    
    
    
}












