<?php

/**
 * FotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Foto');
    }
}