<?php

/**
 * Model
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ThomasCloud
 * @subpackage model
 * @author     Grzegorz Kaszuba
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model extends BaseModel
{
}
