<?php

/**
 * ModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ModelTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Model');
    }

    public function getBrandsArray() {
        $query = $this->createQuery("m");
        $query->select("DISTINCT(m.brand) as brand");
        $data = $query->execute();

        $result = array();

        foreach ($data as $item) {
            $result[$item["brand"]] = $item["brand"];
        }

        return $result;
    }

    public function getModelsArray() {
        $query = $this->createQuery("m");
        $data = $query->execute();

        $result = array();
        
        foreach ($data as $item) {
            $result[$item["brand"]][$item["id"]] = $item["name"];
        }

        return $result;
    }

}