<?php

/**
 * VariantTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VariantTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VariantTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Variant');
    }
}