# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
    .settings:
      enabled_modules:      [default, sfGuardAuth]

    swiftmailer:
      smtp:                 smtp.lukasautohandel.de
      port:                 465
      username:             lukas
      password:             yhexd5629
      fromEmail:            lukas@lukasautohandel.de
      fromUser:             LukasAutoHandel.de administrator
      subject:              E-mail message from lukasautohandel.de
      toEmail:              lukas@lukasautohandel.de