pl:
  url: /pl
  param: {module: default, action: changeLanguage, lang: pl }
en:
  url: /en
  param: {module: default, action: changeLanguage, lang: en }

show_news:
  url: /news/:id/:date/:title
  param: {module: default, action: showNews }
addnews:
  url: /add-news
  param: { module: news, action: index }
news:
  url: /news
  param: { module: default, action: news }
bio:
  url: /bio
  param: { module: default, action: bio }
  
music:
  url: /music
  param: { module: default, action: music }

radio:
  url: /radio
  param: { module: default, action: radio }

schedule:
  url: /schedule
  param: { module: default, action: schedule }

video:
  url: /video
  param: { module: default, action: video }

press:
  url: /press
  param: { module: default, action: press }

contact:
  url: /contact
  param: { module: default, action: contact }

# / dzialy na stronie
sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
language:
  url: /change-language/:lang
  param: { module : default, action: changeLanguage }
  
intro:
  url:   /
  param: { module: default, action: index }
homepage:
  url:   /main
  param: { module: default, action: main }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
