car:
  class: sfDoctrineRouteCollection
  options:
    model:                Car
    module:               cars
    prefix_path:          /cars
    column:               id
    with_wildcard_routes: true
    
search:
  url: /search
  param: {module: default, action: search }
  
search_reset:
  url: /search/reset
  param: {module: default, action: search, _reset: true }
  
contact:
  url: /contact
  param: {module: default, action: contact }
  
contact_ask:
  url: /contact/:id
  class: sfDoctrineRoute
  options:
    model:                Car
    column:               id
    type:                 object
  requirements:
    sf_method: [get,post]
  param: {module: default, action: contact }
  
language:
  url: /language/:lang
  param: { module : default, action: changeLanguage }

show:
  url: /:id/:slug
  param: {module: default, action: show }
  class: sfDoctrineRoute
  options:
    model:                Car
    column:               id
    type:                 object
  
  
homepage:
  url:   /
  param: { module: default, action: index }

default:
  url:   /:module/:action/*
