# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Lukas Autohandel
    description:  Lukas Autohandel
    keywords:     car, auto, samochód
    language:     en,pl,de
    robots:       index, follow

  stylesheets:
    - bootstrap.css
    - slider.css
    - jqtransform.css
    - prettyPhoto.css
    - style.css
  javascripts:
    - jquery-1.10.2.min.js
#    - jquery-1.7.1.min.js
    - /js/vendor/jquery-migrate-1.2.1.js
    - /js/vendor/bootstrap.js
    - /js/vendor/modernizr-2.5.3.min.js
    - jquery.mobile.customized.min.js
    - jquery.easing.1.3.js
    - camera.js
    - superfish.js
    - jquery.jqtransform.js
    - jquery.hoverIntent.minified.js
    - jquery.mobilemenu.js
    - jquery.ui.totop.js
    - jquery.prettyPhoto.js
    - script.js
    - main.js
  has_layout:     true
  layout:         layout
