<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/09/22 22:56:23
sfConfig::add(array(
  'app_enabled_modules' => array (
  0 => 'default',
  1 => 'sfGuardGroup',
  2 => 'sfGuardUser',
  3 => 'sfGuardPermission',
),
));
