<?php
// auto-generated by sfViewConfigHandler
// date: 2012/09/22 23:00:55
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Thomas Cloud Official Site Administration Panel', false, false);
  $response->addMeta('description', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('keywords', 'dj, muzyka', false, false);
  $response->addMeta('language', 'en,pl,pt', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('ui-lightness/jquery-ui-1.8.21.custom.css', '', array ());
  $response->addStylesheet('keyboard.css', '', array ());
  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('/css/vendor/960.gs/960_16_col.css', '', array ());
  $response->addStylesheet('/css/vendor/jquery-ui-timepicker-addon.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('/js/vendor/jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-1.8.21.custom.min.js', '', array ());
  $response->addJavascript('/js/vendor/modernizr-2.5.3.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-sliderAccess.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-timepicker-addon.js', '', array ());
  $response->addJavascript('/js/vendor/bootstrap.min.js', '', array ());
  $response->addJavascript('/js/main.js', '', array ());


