generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Car
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          car
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~  
      fields:  ~
      list:
        title:              "Lista pojazdów"
        batch_actions:      {}
        display:            
          - title
          - price
          - promoted
          - slider
          - created_at
        layout:             stacked
        object_actions:
          edit: {label: zmień, action: edit}
#          _edit:      ~
          _delete: {label: usuń }
        actions:
          new: {label: dodaj, action: addNewCar}
      filter:
        class:  false
      form:    ~
      edit:    ~
      new:     ~
