generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Car
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          car
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:              "Lista pojazdów"
        display:            
          - title
          - price
          - created_at
        layout:             stacked
      filter:
        class:  false
      form:    ~
      edit:    ~
      new:     ~
