<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/08 01:44:48
sfConfig::add(array(
  'app_enabled_modules' => array (
  0 => 'default',
  1 => 'sfGuardAuth',
),
  'app_swiftmailer_smtp' => 'smtp.lukasautohandel.de',
  'app_swiftmailer_port' => 465,
  'app_swiftmailer_username' => 'lukas',
  'app_swiftmailer_password' => 'yhexd5629',
  'app_swiftmailer_fromEmail' => 'lukas@lukasautohandel.de',
  'app_swiftmailer_fromUser' => 'LukasAutoHandel.de administrator',
  'app_swiftmailer_subject' => 'E-mail message from lukasautohandel.de',
  'app_swiftmailer_toEmail' => 'lukas@lukasautohandel.de',
));
