<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/22 22:56:44

return array(
'ThomasCloud' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=thomascloud',
  'username' => 'root',
  'password' => 'root',
  'name' => 'ThomasCloud',
)),);
