<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/07 13:02:28

return array(
'LukasAutohandel' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lukasautohandel',
  'username' => 'root',
  'password' => 'root',
  'name' => 'LukasAutohandel',
)),);
