<?php
// auto-generated by sfViewConfigHandler
// date: 2012/09/22 22:56:58
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'indexSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else if ($this->actionName.$this->viewName == 'videoSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'indexSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'intro' ? false : 'intro'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('description', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('keywords', 'dj, muzyka', false, false);
  $response->addMeta('language', 'en,pl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);


}
else if ($templateName.$this->viewName == 'videoSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('description', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('keywords', 'dj, muzyka', false, false);
  $response->addMeta('language', 'en,pl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('ui-lightness/jquery-ui-1.8.21.custom.css', '', array ());
  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('/css/vendor/960.gs/960_16_col.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('/css/vendor/prettyPhoto.css', '', array ());
  $response->addJavascript('/js/vendor/jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-1.8.21.custom.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-sliderAccess.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-timepicker-addon.js', '', array ());
  $response->addJavascript('/js/vendor/modernizr-2.5.3.min.js', '', array ());
  $response->addJavascript('main.js', '', array ());
  $response->addJavascript('/js/vendor/jquery.prettyPhoto.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('description', 'Thomas Cloud Official Site', false, false);
  $response->addMeta('keywords', 'dj, muzyka', false, false);
  $response->addMeta('language', 'en,pl', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('ui-lightness/jquery-ui-1.8.21.custom.css', '', array ());
  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('/css/vendor/960.gs/960_16_col.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('/js/vendor/jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-1.8.21.custom.min.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-sliderAccess.js', '', array ());
  $response->addJavascript('/js/vendor/jquery-ui-timepicker-addon.js', '', array ());
  $response->addJavascript('/js/vendor/modernizr-2.5.3.min.js', '', array ());
  $response->addJavascript('main.js', '', array ());
}

