all:
  has_layout: true
#indexSuccess:
#  has_layout: true
#  layout:     intro
#  stylesheets: [-*]
#  javascripts: [-*]
videoSuccess:  
  stylesheets:
    - /css/vendor/prettyPhoto.css
  javascripts:
    - /js/vendor/jquery.prettyPhoto.js