Car:
  actAs:
    I18n:
      fields:
        - title
        - description
        - color
        - fuel
        - engine
        - country
        - price
    Timestampable: ~
    Sluggable:
      name:     slug
      fields:
        - title
  tableName:    cars
  columns:
#    model_id:
#      type:     integer
#    variant_id:
#      type:     integer
    model:
      type:     string
      length:   1024
    brand:
      type:     string
      length:   1024
    variant:
      type:     string
      length:   1024
    title:
      type:     string
      length:   1024
    description:
      type:     text
    year:
      type:     string
      length:   1024
    distance:
      type:     integer
      notnull:  true
    fuel:
      type:     string
      length:   1024
    engine:
      type:     string
      length:   1024
    transmission:
      type:     enum
      values:
        - manual
        - automatic
        - semi-auto
    color:
      type:     string
      length:   1024
    country:
      type:     string
      length:   1024
    price:
      type:     string
      length:   1024
    promoted:
      type:     boolean
    slider:
      type:     boolean
  relations:
#    Variant:
#      local:    variant_id
#      foreign:  id
#    Model:
#      local:    model_id
#      foreign:  id
    Fotos:
      type:       many
      class:      Foto
      local:      id
      foreign:    car_id
      onDelete:   CASCADE

#Variant:
#  tableName:    variants
#  columns:
#    name:
#      type:     string
#      length:   1024
#     
#Model:
#  tableName:    models
#  columns:
#    name:
#      type:     string
#      length:   1024
#    brand:
#      type:     string
#      length:   1024

Foto:
  actAs:
    Timestampable: ~
  tableName:    fotos
  columns:
    filename:
      type:     text
      length:   1024
    car_id:
      type:     integer
      default:  null
    is_primary:
      type:     boolean
      default:  false
  relations:
    Car:
      type:       one
      local:      car_id
      onDelete:   SET NULL
